import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
}

// Legacy CDN media passphrase — never in source control. First hit wins:
//
//   1. media.properties      untracked, the normal path for a test build.
//                            Copy media.properties.example and fill it in.
//   2. local.properties      untracked; kept so existing setups keep working.
//   3. NIYAM_MEDIA_PASSPHRASE  env var, for CI.
//
// media.properties is its own file rather than another line in
// local.properties because local.properties is regenerated by Android Studio
// whenever the SDK path changes, which silently drops anything else in it —
// and a build that quietly loses its key looks exactly like a build that never
// had one.
//
// An empty value is a supported build, not a failure: Sounds shows the
// no-media-key state and downloads stay disabled. That path is the first item
// on the QA checklist, so it must keep working.
val mediaPassphrase: String = run {
    fun fromFile(name: String): String? {
        val f = rootProject.file(name)
        if (!f.exists()) return null
        val props = Properties()
        f.inputStream().use { props.load(it) }
        return props.getProperty("niyam.mediaPassphrase")?.trim()?.takeIf { it.isNotEmpty() }
    }
    fromFile("media.properties")
        ?: fromFile("local.properties")
        ?: System.getenv("NIYAM_MEDIA_PASSPHRASE")?.trim()?.takeIf { it.isNotEmpty() }
        ?: ""
}

// Present or absent, and nothing else — not the value, not even its length,
// since build logs get pasted into issues. Without this line the only way to
// tell a keyed build from a keyless one is to install it and open Sounds.
logger.lifecycle(
    if (mediaPassphrase.isEmpty()) {
        "niyam: media key ABSENT — doha downloads disabled in this build"
    } else {
        "niyam: media key present — doha downloads enabled"
    },
)

android {
    namespace = "org.dhamma.gong"
    compileSdk = 35

    defaultConfig {
        applicationId = "org.dhamma.gong"
        // 29 per design doc §03: uniform scoped storage + SAF (doha folder),
        // dependable LocalOnlyHotspot, still covers recycled centre hardware.
        minSdk = 29
        targetSdk = 35
        versionCode = 5
        versionName = "0.2.0-beta4"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField(
            "String",
            "MEDIA_PASSPHRASE",
            "\"${mediaPassphrase.replace("\\", "\\\\").replace("\"", "\\\"")}\"",
        )
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        compose = true
        buildConfig = true
    }
    testOptions {
        unitTests {
            isIncludeAndroidResources = true
        }
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

// Room schema JSON is checked in, so a migration is a reviewable diff.
ksp {
    arg("room.schemaLocation", "$projectDir/schemas")
    arg("room.generateKotlin", "true")
}

dependencies {
    val composeBom = platform(libs.androidx.compose.bom)
    implementation(composeBom)
    androidTestImplementation(composeBom)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.lifecycle.service)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation(libs.androidx.navigation.compose)
    debugImplementation(libs.androidx.ui.tooling)

    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)
    ksp(libs.androidx.room.compiler)

    implementation(libs.androidx.media3.exoplayer)
    implementation(libs.androidx.media3.common)

    implementation(libs.androidx.datastore.preferences)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.coroutines.android)

    testImplementation(libs.junit)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.androidx.room.testing)
    testImplementation(libs.kotlinx.coroutines.test)

    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.ui.test.junit4)
    debugImplementation(libs.androidx.ui.test.manifest)
}
